# APT packages that don't get installed by a role
apt_packages:
  - lsb-release
  - htop
  - lsof
  - strace
  - tmux
  - cron
  - gddrescue
  - pv
  - testdisk
  - fzf
  - fd-find
  - ripgrep
  - rsync
