version: "3.3"
services:
  local_postgres:
    # Official PostgreSQL image
    # https://registry.hub.docker.com/u/library/postgres/
    # TODO: convert the data files to the latest version (10), then change the image back to "postgres:latest"
    image: postgres:9.6
    container_name: local_postgres
    # Those are also the default values, left here for clarity. This will be the superuser.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # https://docs.docker.com/compose/compose-file/#/expose
    expose:
      - "5432"
    # https://docs.docker.com/compose/compose-file/#/ports
    ports:
      - "5440:5432"
    # Use a separate volume that is persisted even if the container is deleted
    volumes:
      - local_postgres_data:/var/lib/postgresql/data

# https://docs.docker.com/compose/compose-file/#volume-configuration-reference
# https://docs.docker.com/engine/admin/volumes/volumes/
volumes:
  local_postgres_data:
