version: "3.5"

# https://docs.docker.com/compose/compose-file/#volume-configuration-reference
# https://docs.docker.com/engine/admin/volumes/volumes/
volumes:
  data10:
    driver: local
    name: postgres10

networks:
  net10:
    name: postgres10

services:
  postgres10:
    # https://registry.hub.docker.com/u/library/postgres/
    image: postgres:10
    restart: always
    container_name: postgres10
    # Those are also the default values, left here for clarity. This will be the superuser.
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # https://docs.docker.com/compose/compose-file/#/expose
    expose:
      - "5432"
    # https://docs.docker.com/compose/compose-file/#/ports
    ports:
      - "7710:5432"
    # Use a separate volume that is persisted even if the container is deleted
    volumes:
      - data10:/var/lib/postgresql/data
      - ~/Dropbox/Backup:/var/backups/
    networks:
      - net10
