# Info on all modules: http://xon.sh/xontribs.html
xontribs_install:
  - xonsh-autoxsh
  - xontrib-z
  - pyyaml

xontribs_load:
  # Pre-installed modules
  - jedi  # https://xon.sh/xontribs.html#jedi
  - prompt_ret_code  # https://xon.sh/xontribs.html#prompt-ret-code
  - whole_word_jumping  # https://xon.sh/xontribs.html#whole-word-jumping

  # Installed modules: http://xon.sh/tutorial_xontrib.html
  - autoxsh  # https://xon.sh/xontribs.html#autoxsh
  - z  # https://xon.sh/xontribs.html#z
