- name: "gitup : Create config directory"
  file:
    state: directory
    path: "~/.config/gitup/"

- name: "gitup : List all repos on the home directory"
  shell: "find ~ -type d -name .git -exec dirname {} \\; > ~/.config/gitup/all_home_repos"
  register: last_execution_gitup
  when: "'gitup_list_all_repos' | run_only_after"
  ignore_errors: yes # TODO failing with several "Operation not permitted" messages

- name: "gitup : Clean bookmarks"
  command: "gitup --bookmark-file ~/.config/gitup/{{ item }} --clean"
  when: last_execution_gitup is not skipped
  with_items:
    - bookmarks
    - manual_update

- name: "gitup : Update repos"
  command: "gitup"
  when: last_execution_gitup is not skipped
  register: gitup_update_repos
- debug: var=gitup_update_repos.stdout_lines

- name: "gitup : Fetch repos with manual update"
  command: "gitup --bookmark-file ~/.config/gitup/manual_update --fetch-only --prune"
  when: last_execution_gitup is not skipped
  register: gitup_fetch_manual_repos
- debug: var=gitup_fetch_manual_repos.stdout_lines

- name: "gitup : Touch file to avoid executing again"
  file:
    state: touch
    path: ~/.config/gitup/last_execution
  when: last_execution_gitup is not skipped
