latest_python_3_6: 3.6.4
latest_python_3_5: 3.5.4
latest_python_3_4: 3.4.7
latest_python_2_7: 2.7.14

python2_modules:
  - rename

python3_modules:
  - pipenv
  - youtube-dl
  - cookiecutter
  - cookiepatcher
  - organize-tool
  - black
